version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "6500:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    env_file:
      - ../server/.env
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    env_file:
      - ../server/.env
    ports:
      - "5050:80"